
server:
  port: 8080
  servlet:
    context-path: /romannumeral

spring:
  application:
    name: adobe-roman-numerals
    version: 1.0.0

logging:
  level:
    root: INFO
    com.adobe.assessment.romannumerals: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

numeral-to-roman:
  range:
    min: 1
    max: 3999
